services:
  web:
    build:
      context: .
      target: dev
      args:
        NODE_ENV: development
        BASE_IMAGE: focal

    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=screamshotter.settings.dev
      - COLLECTSTATIC=0
      - EXTERNAL_PUPPETEER=wss://chrome.paas.kasta.ovh:443

