version: '3'
services:
  web:
    build:
      context: .
      target: dev
      args:
        - NODE_ENV=development
    volumes:
      - ./src/:/app/src/
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=screamshotter.settings.dev
      - COLLECTSTATIC=0
