#!/bin/sh -e

adduser --system --group --no-create-home --quiet screamshotter || true
mkdir -p /var/log/screamshotter || true
chown screamshotter.screamshotter /var/log/screamshotter || true

#DEBHELPER#
