name: Publish debian package and docker image

on:
  workflow_run:
    workflows:
      - Test CI
    types:
      - completed
    releases: '*'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - name: Download 18.04 debian artifact
        uses: actions/download-artifact@v2
        with:
          name: debian-18-04
      - name: Download 20.04 debian artifact
        uses: actions/download-artifact@v2
        with:
          name: debian-20-04
      - name: Download docker image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "screamshotter_ci:latest"
      - name: Publish docker image
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
          docker tag screamshotter_ci:latest makinacorpus/screamshotter:v2
          docker push makinacorpus/screamshotter:v2
      - name: Attach debian packages as release binaries
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '/home/runner/work/screamshotter/screamshotter_*_amd64.deb'
      - name: Publish debian packages
        run: |
          grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' VERSION && export DEB_COMPONENT=main || export DEB_COMPONENT=dev
          scp -P $SSH_PORT -o StrictHostKeyChecking=no /home/runner/work/screamshotter/screamshotter_*_amd64.deb $SSH_USER@$SSH_HOST:/srv/packages/incoming/$DEB_COMPONENT/
          ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST make -C /srv/packages
